version: '3.8'

services:
  # Serviço para a aplicação (API + Frontend)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appraizes-app
    restart: always
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST:-207.180.249.172}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-Fatec555133}
      - DB_NAME=${DB_NAME:-appraizes_db}
      - API_PORT=3001
    ports:
      - "3001:3001"
      - "5173:5173"
    networks:
      - appraizes-network
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs

  # Serviço para o servidor web Nginx (opcional, para produção)
  nginx:
    image: nginx:alpine
    container_name: appraizes-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
    depends_on:
      - app
    networks:
      - appraizes-network

networks:
  appraizes-network:
    driver: bridge
